version: "3.8"
services:
  database:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pmoreira
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5433"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
